# Generated by Django 2.2.7 on 2019-11-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='氏名')),
                ('year', models.DateField(verbose_name='生年月日')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='出勤時間')),
                ('finish_time', models.TimeField(verbose_name='退勤時間')),
                ('woker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Worker', verbose_name='労働者')),
            ],
        ),
    ]
